[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
  | venv/
  | .idea/
)/'''


[tool.isort]
profile = "hug"
src_paths = ["account", "bills", "pet_project_django", "user_profile"]