# Generated by Django 3.2.7 on 2021-10-01 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="account.account"),
        ),
    ]
