name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=8 `ls -R|grep .py$|xargs`
